// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD318Sye01v0WCjWC6OaR2UXOcTqFUreQM',
    appId: '1:713737911363:web:5ddf224cba9a618b9568f6',
    messagingSenderId: '713737911363',
    projectId: 'application-siloe',
    authDomain: 'application-siloe.firebaseapp.com',
    storageBucket: 'application-siloe.firebasestorage.app',
    measurementId: 'G-70LMXC7CXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg95LCiKkbIE2rgdt2A1vmsm6ZvFxoBsU',
    appId: '1:713737911363:android:8234380de7303d9a9568f6',
    messagingSenderId: '713737911363',
    projectId: 'application-siloe',
    storageBucket: 'application-siloe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EJJI24zdCnI_K-6y5v81iN5y8sUjQsE',
    appId: '1:713737911363:ios:d36f64a13040a6ce9568f6',
    messagingSenderId: '713737911363',
    projectId: 'application-siloe',
    storageBucket: 'application-siloe.firebasestorage.app',
    iosClientId: '713737911363-ehdbeaqn7ca1itreftqndq92f23lskc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.siloeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EJJI24zdCnI_K-6y5v81iN5y8sUjQsE',
    appId: '1:713737911363:ios:d36f64a13040a6ce9568f6',
    messagingSenderId: '713737911363',
    projectId: 'application-siloe',
    storageBucket: 'application-siloe.firebasestorage.app',
    iosClientId: '713737911363-ehdbeaqn7ca1itreftqndq92f23lskc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.siloeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD318Sye01v0WCjWC6OaR2UXOcTqFUreQM',
    appId: '1:713737911363:web:25636dfd8eaf51449568f6',
    messagingSenderId: '713737911363',
    projectId: 'application-siloe',
    authDomain: 'application-siloe.firebaseapp.com',
    storageBucket: 'application-siloe.firebasestorage.app',
    measurementId: 'G-WK4C9Q6FZL',
  );
}
